name: Update
permissions:
  contents: write

on:
  schedule:
    - cron: "23 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Update
        run: ./gradlew run

      - name: Push updated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions-bot
          author_email: github-actions[bot]@users.noreply.github.com
