name: Update
permissions:
  contents: write

on:
  schedule:
    - cron: "23 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Validate Gradle Wrapper Integrity
        uses: gradle/wrapper-validation-action@v2

      - name: Update
        run: ./gradlew run

      - name: Push updated files
        # If all files are identical this will do nothing, no need to check.
        run: |
          git config --global user.name github-actions-bot
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update"
          git push
